repositories:
  - name: jitesoft
    url: https://jitesoft.github.io/helm-charts  # Jitesoft's Helm chart repository

releases:
  - name: alpine
    namespace: argo
    chart: jitesoft/alpine  # The chart name from the repository
    version: latest  # Specify the desired version of the chart
    values:
      - values.yaml  # Reference to a values file for custom configurations

